### ISSUE TITLE
Support valid shell commands including quotes and spaces

### ISSUE THREAD

**Issue by KylePDavis** [tombell/test-status#40]
I need the ability to run any valid shell command.

Specifically, I need the ability to run something like this:
`TEST_FLAG_A=1 TEST_FLAG_B="foo bar" npm test`

This was working after #37 but was reverted to fix #39.

I'd like to get this working again but hopefully without breaking the use case in #39.

**Comment by tombell** [comment]
Fixed in c85ac4dd890ec861d851f551580cccf4a2178089
