### ISSUE TITLE
Jest tests fail when run within test-status because of NODE_ENV set to 'production'

### ISSUE THREAD

**Issue by ronjouch** [tombell/test-status#45]
Hi.

A [jest](http://facebook.github.io/jest/)-based test suite I have passes all tests from the command-line, but partially fails when run from test-status.

After some investigation, the spawned process/arguments command line is identical, but the culprit variation is the `NODE_ENV` environment variable, which is:

* Unset in my terminal.
* Set to `"production"` within Atom.

Proof is that a. setting `NODE_ENV` in the terminal also break the tests in the terminal, b. this ugly patch to your `command-runner.coffee` fixes the tests in Atom:

``` coffeescript
  execute: (cmd) ->
    ...

    try
      # make a shallow copy of the environment variables, and set NODE_ENV to empty string
      modifiedEnv = {}
      for k in Object.keys(process.env)
        modifiedEnv[k] = process.env[k]
      modifiedEnv.NODE_ENV = ''

      proc = spawn(cmd.shift(), cmd, {cwd: atom.project.path, env: modifiedEnv})
      # used to be: proc = spawn(cmd.shift(), cmd, cwd: atom.project.path)
```

Failing tests fail somewhere in jest-cli / jasmine, e.g.

```
● Module › it renders a module with the proper size
  - TypeError: Cannot call method 'renderIntoDocument' of undefined
        at Spec.<anonymous> (/home/rjouchet/workspace/es/es/js/common/components/__tests__/Module.test.jsx:19:28)
        at jasmine.Block.execute (/home/rjouchet/workspace/es/node_modules/jest-cli/vendor/jasmine/jasmine-1.3.0.js:1065:17)
        at jasmine.Queue.next_ (/home/rjouchet/workspace/es/node_modules/jest-cli/vendor/jasmine/jasmine-1.3.0.js:2098:31)
        at null._onTimeout (/home/rjouchet/workspace/e/node_modules/jest-cli/vendor/jasmine/jasmine-1.3.0.js:2088:18)
        at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
```

→ Would unsetting `NODE_ENV` sound reasonable to you? Do you see anything else that can be done?

Anyway, thanks a lot for your work, it's a great addition to develop on test-heavy projects :)

**Comment by svnlto** [comment]
just ran into this as well..

**Comment by ronjouch** [comment]
@svnlto does my ugly patch in comment 1 work for you? I'd propose a Pull Request, but I don't know Node.js/Atom ecosystem enough to judge whether my hack is a potential solution, or would just break things for other users :/

**Comment by Poltergeist** [comment]
If you come across this just use `NODE_ENV=test moch` or whatever test command you have in your `package.json`. Had the same problem, this solution is probably the best practice way to do it anyway.
