### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by stjohnjohnson** [tombell/test-status#48]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:53:11)
Object.activate (/Users/stjohn/.atom/packages/test-status/lib/test-status.coffee:16:12)
```

**Comment by tombell** [comment]
Fixed in 2e1cde88dd60c8ff72fd93a66b8ea98c56756404
